plugins {
    id 'com.android.application'
}

android {
    namespace 'com.astroknights.turnorder'
    compileSdk 34

    defaultConfig {
        applicationId "com.astroknights.turnorder"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Alinea todas las librerías de Kotlin a la misma versión (evita clases duplicadas)
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
